#!/usr/bin/env python3
"""Generate Alembic migration scripts from SQLAlchemy models."""

import os
import sys
from datetime import datetime
from pathlib import Path


def generate_initial_migration(output_dir: str, entities: list[str]) -> str:
    """Generate 001_initial_schema.py migration."""
    revision_id = "001_initial_schema"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    migration_code = f'''"""Initial schema migration

Revision ID: {revision_id}
Revises:
Create Date: {timestamp}

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '{revision_id}'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Create all tables."""
    # This will be auto-generated by Alembic based on models
    pass


def downgrade():
    """Drop all tables."""
    # This will be auto-generated by Alembic based on models
    pass
'''

    os.makedirs(output_dir, exist_ok=True)
    migration_path = os.path.join(output_dir, f"{revision_id}.py")

    with open(migration_path, 'w') as f:
        f.write(migration_code)

    return migration_path


def setup_alembic(backend_path: str):
    """Set up Alembic configuration."""
    alembic_ini = f'''# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = database/migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to database/migrations/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path.
# The path separator used here should be the separator specified by "version_path_separator" below.
# version_locations = %(here)s/bar:%(here)s/bat:database/migrations/versions

# version path separator; As mentioned above, this is the character used to split
# version_locations. The default within new alembic.ini files is "os", which uses os.pathsep.
# If this key is omitted entirely, it falls back to the legacy behavior of splitting on spaces and/or commas.
# Valid values for version_path_separator are:
#
# version_path_separator = :
# version_path_separator = ;
# version_path_separator = space
version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# format using "black" - use the console_scripts runner, against the "black" entrypoint
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
'''

    alembic_ini_path = os.path.join(backend_path, "alembic.ini")
    with open(alembic_ini_path, 'w') as f:
        f.write(alembic_ini)

    # Create migrations directory structure
    migrations_dir = os.path.join(backend_path, "database", "migrations")
    versions_dir = os.path.join(migrations_dir, "versions")
    os.makedirs(versions_dir, exist_ok=True)

    # Create env.py
    env_py = '''from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Import your Base and models
import sys
import os
sys.path.append(os.path.abspath('.'))
from database.models import Base

# this is the Alembic Config object
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# add your model's MetaData object here for 'autogenerate' support
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''

    env_py_path = os.path.join(migrations_dir, "env.py")
    with open(env_py_path, 'w') as f:
        f.write(env_py)

    # Create script.py.mako template
    script_mako = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}
'''

    script_mako_path = os.path.join(migrations_dir, "script.py.mako")
    with open(script_mako_path, 'w') as f:
        f.write(script_mako)

    return alembic_ini_path


def main():
    backend_path = "backend"

    # Set up Alembic
    alembic_ini = setup_alembic(backend_path)

    # Generate initial migration placeholder
    migrations_dir = os.path.join(backend_path, "database", "migrations", "versions")
    migration_file = generate_initial_migration(migrations_dir, [])

    print(f"✓ Generated Alembic configuration in {alembic_ini}")
    print(f"✓ Generated migration template in {migration_file}")
    print(f"\nNext steps:")
    print(f"  1. Configure database URL in alembic.ini")
    print(f"  2. Run: alembic revision --autogenerate -m 'Initial schema'")
    print(f"  3. Run: alembic upgrade head")


if __name__ == "__main__":
    main()
