"""
SQLAlchemy ORM models for EmberLearn database.

Auto-generated from data-model.md specification.
"""

from datetime import datetime
from typing import Optional
from uuid import UUID

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float, ForeignKey,
    Integer, Numeric, String, Text, func, text
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class User(Base):
    """
    Students, teachers, and admins with authentication and profile data.
    """
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True, autoincrement=True)
    uuid = Column(UUID, nullable=False, unique=True, server_default=text('gen_random_uuid()'))
    email = Column(String(255), nullable=False, unique=True)
    password_hash = Column(String(255), nullable=False)
    role = Column(Enum('STUDENT', " 'TEACHER", " 'ADMIN", name='STUDENT_enum'), nullable=False, default="'student'")
    first_name = Column(String(100), nullable=False)
    last_name = Column(String(100), nullable=False)
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now())
    last_login_at = Column(DateTime)


class Topic(Base):
    """
    Python curriculum modules (8 topics from spec: Basics, Control Flow, Data Structures, Functions, OOP, Files, Errors, Libraries).
    """
    __tablename__ = 'topic'

    id = Column(Integer, primary_key=True, autoincrement=True)
    slug = Column(String(100), nullable=False, unique=True)
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=False)
    order = Column(Integer, nullable=False)
    created_at = Column(DateTime, nullable=False, server_default=func.now())


class Progress(Base):
    """
    Track student mastery per topic using weighted formula.
    """
    __tablename__ = 'progress'

    user_id = Column(Integer, nullable=False)
    topic_id = Column(Integer, nullable=False)
    exercise_completion_pct = Column(Numeric, nullable=False, default='0.00')
    quiz_score_avg = Column(Numeric, nullable=False, default='0.00')
    code_quality_avg = Column(Numeric, nullable=False, default='0.00')
    consistency_score = Column(Numeric, nullable=False, default='0.00')
    mastery_score = Column(Numeric, nullable=False, default='0.00')
    mastery_level = Column(Enum('BEGINNER', " 'LEARNING", " 'PROFICIENT", " 'MASTERED", name='BEGINNER_enum'), nullable=False, default="'beginner'")
    last_activity_at = Column(DateTime, nullable=False, server_default=func.now())
    updated_at = Column(DateTime, nullable=False, server_default=func.now())


class Exercise(Base):
    """
    Coding challenges generated by Exercise agent or pre-defined.
    """
    __tablename__ = 'exercise'

    id = Column(Integer, primary_key=True, autoincrement=True)
    uuid = Column(UUID, nullable=False, unique=True, server_default=text('gen_random_uuid()'))
    topic_id = Column(Integer, nullable=False)
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    difficulty = Column(Enum('EASY', " 'MEDIUM", " 'HARD", name='EASY_enum'), nullable=False)
    starter_code = Column(Text, nullable=False, default="''")
    solution_code = Column(Text, nullable=False)
    created_by = Column(Integer)
    created_at = Column(DateTime, nullable=False, server_default=func.now())


class TestCase(Base):
    """
    Validation criteria for exercises (input → expected output).
    """
    __tablename__ = 'testcase'

    id = Column(Integer, primary_key=True, autoincrement=True)
    exercise_id = Column(Integer, nullable=False)
    input_data = Column(Text, nullable=False)
    expected_output = Column(Text, nullable=False)
    is_hidden = Column(Boolean, nullable=False, default='FALSE')
    weight = Column(Numeric, nullable=False, default='1.00')
    created_at = Column(DateTime, nullable=False, server_default=func.now())


class ExerciseSubmission(Base):
    """
    Student attempts at exercises with auto-grading results.
    """
    __tablename__ = 'exercisesubmission'

    id = Column(Integer, primary_key=True, autoincrement=True)
    uuid = Column(UUID, nullable=False, unique=True, server_default=text('gen_random_uuid()'))
    user_id = Column(Integer, nullable=False)
    exercise_id = Column(Integer, nullable=False)
    code = Column(Text, nullable=False)
    execution_result = Column(String(255), nullable=False)
    test_results = Column(String(255), nullable=False)
    passed_count = Column(Integer, nullable=False, default='0')
    total_count = Column(Integer, nullable=False)
    score = Column(Numeric, nullable=False, default='0.00')
    code_quality_rating = Column(Numeric)
    status = Column(Enum('PENDING', " 'PASSED", " 'FAILED", " 'ERROR", name='PENDING_enum'), nullable=False, default="'pending'")
    submitted_at = Column(DateTime, nullable=False, server_default=func.now())


class Quiz(Base):
    """
    Multiple-choice assessments per topic.
    """
    __tablename__ = 'quiz'

    id = Column(Integer, primary_key=True, autoincrement=True)
    topic_id = Column(Integer, nullable=False)
    question = Column(Text, nullable=False)
    options = Column(String(255), nullable=False)
    correct_answer = Column(String(1), nullable=False)
    explanation = Column(Text, nullable=False)
    created_at = Column(DateTime, nullable=False, server_default=func.now())


class QuizAttempt(Base):
    """
    Student quiz attempts with scores.
    """
    __tablename__ = 'quizattempt'

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False)
    topic_id = Column(Integer, nullable=False)
    answers = Column(String(255), nullable=False)
    correct_count = Column(Integer, nullable=False, default='0')
    total_count = Column(Integer, nullable=False)
    score = Column(Numeric, nullable=False, default='0.00')
    completed_at = Column(DateTime, nullable=False, server_default=func.now())


class StruggleAlert(Base):
    """
    Detect and alert teachers when students are struggling.
    """
    __tablename__ = 'strugglealert'

    id = Column(Integer, primary_key=True, autoincrement=True)
    uuid = Column(UUID, nullable=False, unique=True, server_default=text('gen_random_uuid()'))
    user_id = Column(Integer, nullable=False)
    topic_id = Column(Integer)
    trigger_type = Column(Enum('SAME_ERROR_3X', " 'STUCK_10MIN", " 'QUIZ_FAIL", " 'EXPLICIT_HELP", " 'FAILED_EXECUTIONS_5X", name='SAME_ERROR_3X_enum'), nullable=False)
    trigger_data = Column(String(255), nullable=False)
    severity = Column(Enum('LOW', " 'MEDIUM", " 'HIGH", name='LOW_enum'), nullable=False, default="'medium'")
    resolved = Column(Boolean, nullable=False, default='FALSE')
    resolved_by = Column(Integer)
    resolved_at = Column(DateTime)
    created_at = Column(DateTime, nullable=False, server_default=func.now())


